-- Voorbeeldwoningen (optioneel). Uitvoeren na schema.sql.
-- Verwijderen kan later per woning in de beheeromgeving.

insert into public.woningen (slug,titel,plaats,regio,type,huur,servicekosten,borg,oppervlakte,kamers,slaapkamers,energielabel,beschikbaar,status,interieur,kenmerken,voorwaarden,omschrijving,fotos,gepubliceerd,voorbeeld,volgorde) values
  ('middelburg-appartement-balkengracht', 'Licht appartement aan het water', 'Middelburg', 'Walcheren', 'Appartement', 1150, 65, 2300, 74, 3, 2, 'A', '2026-11-01', 'beschikbaar', 'gestoffeerd', array['Balkon op het zuiden','Lift','Berging','Nabij centrum en station']::text[], array['Bruto inkomen minimaal 3× de huur','Geen huisdieren','Niet roken']::text[], 'Ruim en licht driekamerappartement op loopafstand van de binnenstad en het station van Middelburg. De woonkamer heeft grote ramen en toegang tot een zonnig balkon.

De open keuken is voorzien van inbouwapparatuur. Het appartement wordt gestoffeerd opgeleverd met vloeren en raambekleding.', array[]::text[], true, true, 0),
  ('goes-eengezinswoning-oostzijde', 'Eengezinswoning met tuin', 'Goes', 'Zuid-Beveland', 'Eengezinswoning', 1395, 0, 2790, 112, 5, 3, 'B', null, 'beschikbaar', 'kaal', array['Achtertuin met schuur','Parkeren voor de deur','Scholen in de buurt','Zolder als 4e slaapkamer']::text[], array['Bruto inkomen minimaal 3× de huur','Huisdieren in overleg','Minimale huurperiode 12 maanden']::text[], 'Goed onderhouden tussenwoning in een rustige, kindvriendelijke wijk van Goes. Scholen, winkels en de A58 liggen op korte afstand.

Beneden een doorzonwoonkamer en een dichte keuken; boven drie slaapkamers en een badkamer met douche. De vaste trap naar de zolder biedt ruimte voor een extra kamer.', array[]::text[], true, true, 1),
  ('vlissingen-studio-boulevard', 'Studio vlak bij de boulevard', 'Vlissingen', 'Walcheren', 'Studio', 795, 45, 1590, 34, 1, 1, 'C', '2026-10-15', 'onder optie', 'gemeubileerd', array['Gemeubileerd','Eigen keuken en badkamer','Fietsenstalling','Zee op 3 minuten lopen']::text[], array['Bruto inkomen minimaal 3× de huur','Geschikt voor 1 persoon','Niet roken']::text[], 'Compacte, volledig ingerichte studio op een paar minuten van de boulevard en de hogescholen in Vlissingen. Ideaal voor een starter of iemand die tijdelijk in Zeeland werkt.', array[]::text[], true, true, 2),
  ('zierikzee-bovenwoning-havenpark', 'Karakteristieke bovenwoning', 'Zierikzee', 'Schouwen-Duiveland', 'Bovenwoning', 975, 0, 1950, 68, 3, 2, 'C', '2026-12-01', 'beschikbaar', 'gestoffeerd', array['Historische binnenstad','Eigen opgang','Dakterras','Gerenoveerde badkamer']::text[], array['Bruto inkomen minimaal 3× de huur','Geen huisdieren']::text[], 'Sfeervolle bovenwoning met eigen opgang in de historische binnenstad van Zierikzee. De woning is recent gerenoveerd en heeft een dakterras met uitzicht over de daken.', array[]::text[], true, true, 3),
  ('terneuzen-appartement-centrum', 'Nieuwbouwappartement in het centrum', 'Terneuzen', 'Zeeuws-Vlaanderen', 'Appartement', 1075, 55, 2150, 70, 3, 2, 'A', null, 'beschikbaar', 'gestoffeerd', array['Nieuwbouw','Vloerverwarming','Eigen parkeerplaats','Lift']::text[], array['Bruto inkomen minimaal 3× de huur','Niet roken']::text[], 'Modern en energiezuinig appartement in het centrum van Terneuzen, met een eigen parkeerplaats in de afgesloten garage.', array[]::text[], true, true, 4),
  ('bergen-op-zoom-benedenwoning', 'Benedenwoning met stadstuin', 'Bergen op Zoom', 'Omliggend', 'Benedenwoning', 1025, 0, 2050, 72, 3, 2, 'B', '2026-11-15', 'verhuurd', 'kaal', array['Stadstuin','Nabij station','Eigen voordeur']::text[], array['Bruto inkomen minimaal 3× de huur']::text[], 'Benedenwoning met eigen voordeur en stadstuin, op korte afstand van het station en het centrum van Bergen op Zoom.', array[]::text[], true, true, 5)
on conflict (slug) do nothing;
